### ISSUE TITLE
bl package is vulnerable

### ISSUE THREAD

**Issue by taku0** [ssbc/ssb-invite#13]
`npm audit` reports the following vulnerability.

<table>
<tr><td>Moderate<td>Memory Exposure
<tr><td>Package       <td>bl
<tr><td>Patched in    <td>>=0.9.5 <1.0.0 || >=1.0.1
<tr><td>Dependency of <td>ssb-invite
<tr><td>Path          <td>ssb-invite > level-sublevel > levelup > bl
<tr><td>More info     <td>https://npmjs.com/advisories/596
</table>

[`level-sublevel`](https://github.com/dominictarr/level-sublevel) is no longer maintained. It uses an old version of `levelup` `~0.19.0` where the latest version of `levelup` is `4.3.2`. 

It might be replaced with [`subleveldown`](https://github.com/Level/subleveldown), but I don't sure.

**Comment by dominictarr** [comment]
This is a false positive. It wouldn't actually be possible to steal secrets using this. You'd need to `new Buffer(user_value)` but ssb-invite controls the value on the server side.
